import type { LibraryBookRecord } from "./backend-api";

export const BUILT_IN_LIBRARY_BOOKS: LibraryBookRecord[] = [
  {
    accessLabel: "Built in",
    accessType: "full",
    accentColor: "#D7F0B7",
    actionLabel: "Read",
    author: "James Clear",
    blurb: "A bundled EPUB for habit building, routines, and steady personal change.",
    bundledEpubAsset: require("../assets/books/Atomic Habits (James Clear).epub"),
    category: "Habit Building",
    coverImageUrl: "",
    downloadableEpub: true,
    downloaded: true,
    downloadedAt: null,
    downloadUrl: "",
    estimatedMinutes: 320,
    externalReaderLink: "",
    id: "builtin-atomic-habits",
    isFreeEbook: false,
    language: "eng",
    pageCount: 0,
    previewLink: "",
    provider: "builtin",
    publishedDate: "",
    publisher: "",
    readerLink: "",
    rewardLabel: "Rate after reading",
    shelfLabel: "Built in",
    sourceId: "Atomic Habits (James Clear).epub",
    sourceReaderLink: "",
    statusLabel: "Ready to read",
    supportsInAppReader: true,
    title: "Atomic Habits",
    progress: null,
  },
  {
    accessLabel: "Built in",
    accessType: "full",
    accentColor: "#CFE6F8",
    actionLabel: "Read",
    author: "Ichiro Kishimi, Fumitake Koga",
    blurb: "A bundled EPUB about self-acceptance, courage, and personal responsibility.",
    bundledEpubAsset: require("../assets/books/The Courage to Be Disliked.epub"),
    category: "Self Reflection",
    coverImageUrl: "",
    downloadableEpub: true,
    downloaded: true,
    downloadedAt: null,
    downloadUrl: "",
    estimatedMinutes: 280,
    externalReaderLink: "",
    id: "builtin-courage-to-be-disliked",
    isFreeEbook: false,
    language: "eng",
    pageCount: 0,
    previewLink: "",
    provider: "builtin",
    publishedDate: "",
    publisher: "",
    readerLink: "",
    rewardLabel: "Rate after reading",
    shelfLabel: "Built in",
    sourceId: "The Courage to Be Disliked.epub",
    sourceReaderLink: "",
    statusLabel: "Ready to read",
    supportsInAppReader: true,
    title: "The Courage to Be Disliked",
    progress: null,
  },
  {
    accessLabel: "Built in",
    accessType: "full",
    accentColor: "#E8D7F2",
    actionLabel: "Read",
    author: "Brianna Wiest",
    blurb: "A bundled EPUB for emotional patterns, self-sabotage, and rebuilding from within.",
    bundledEpubAsset: require("../assets/books/The Mountain Is You.epub"),
    category: "Inner Work",
    coverImageUrl: "",
    downloadableEpub: true,
    downloaded: true,
    downloadedAt: null,
    downloadUrl: "",
    estimatedMinutes: 260,
    externalReaderLink: "",
    id: "builtin-the-mountain-is-you",
    isFreeEbook: false,
    language: "eng",
    pageCount: 0,
    previewLink: "",
    provider: "builtin",
    publishedDate: "",
    publisher: "",
    readerLink: "",
    rewardLabel: "Rate after reading",
    shelfLabel: "Built in",
    sourceId: "The Mountain Is You.epub",
    sourceReaderLink: "",
    statusLabel: "Ready to read",
    supportsInAppReader: true,
    title: "The Mountain Is You",
    progress: null,
  },
  {
    accessLabel: "Built in",
    accessType: "full",
    accentColor: "#F8E8BE",
    actionLabel: "Read",
    author: "Dr. Julie Smith",
    blurb: "A bundled EPUB with practical mental health tools for everyday difficult moments.",
    bundledEpubAsset: require("../assets/books/Why_Has_Nobody_Told_Me_This_Before_Dr_Julie_Smith (1).epub"),
    category: "Mental Health",
    coverImageUrl: "",
    downloadableEpub: true,
    downloaded: true,
    downloadedAt: null,
    downloadUrl: "",
    estimatedMinutes: 300,
    externalReaderLink: "",
    id: "builtin-why-has-nobody-told-me-this-before",
    isFreeEbook: false,
    language: "eng",
    pageCount: 0,
    previewLink: "",
    provider: "builtin",
    publishedDate: "",
    publisher: "",
    readerLink: "",
    rewardLabel: "Rate after reading",
    shelfLabel: "Built in",
    sourceId: "Why_Has_Nobody_Told_Me_This_Before_Dr_Julie_Smith (1).epub",
    sourceReaderLink: "",
    statusLabel: "Ready to read",
    supportsInAppReader: true,
    title: "Why Has Nobody Told Me This Before?",
    progress: null,
  },
  {
    accessLabel: "Built in",
    accessType: "full",
    accentColor: "#D7EBE5",
    actionLabel: "Read",
    author: "Eckhart Tolle",
    blurb: "A bundled EPUB about presence, attention, and living with a quieter mind.",
    bundledEpubAsset: require("../assets/books/The Power of Now.epub"),
    category: "Mindfulness",
    coverImageUrl: "",
    downloadableEpub: true,
    downloaded: true,
    downloadedAt: null,
    downloadUrl: "",
    estimatedMinutes: 260,
    externalReaderLink: "",
    id: "builtin-the-power-of-now",
    isFreeEbook: false,
    language: "eng",
    pageCount: 0,
    previewLink: "",
    provider: "builtin",
    publishedDate: "",
    publisher: "",
    readerLink: "",
    rewardLabel: "Rate after reading",
    shelfLabel: "Built in",
    sourceId: "The Power of Now.epub",
    sourceReaderLink: "",
    statusLabel: "Ready to read",
    supportsInAppReader: true,
    title: "The Power of Now",
    progress: null,
  },
];

export const BUILT_IN_LIBRARY_BOOK_IDS = BUILT_IN_LIBRARY_BOOKS.map((book) => book.id);
