export const PROGRAM_OPTIONS = [
  "BECED Early Childhood Education",
  "BSEd Filipino",
  "BSEd Science",
  "BSEd Social Studies",
  "BSEd Mathematics",
  "BSEd English",
  "BS Civil Engineering",
  "BS Electrical Engineering",
  "BS Information Technology",
  "BS Psychology",
  "BA Communication Theater Arts",
  "BS Social Work",
  "BSBA Marketing Management",
  "BSBA Human Resource Development Management",
  "BS Accountancy",
  "BSBA Financial Management",
];

export const BARANGAY_OPTIONS = [
  "Arkong Bato",
  "Bagbaguin",
  "Balangkas",
  "Bignay",
  "Bisig",
  "Canumay East",
  "Canumay West",
  "Coloong",
  "Dalandanan",
  "Gen T De Leon",
  "Isla",
  "Karuhatan",
  "Lawang Bato",
  "Lingunan",
  "Mabolo",
  "Malanday",
  "Malinta",
  "Mapulang Lupa",
  "Marulas",
  "Maysan",
  "Palasan",
  "Parada",
  "Pariancillo Villa",
  "Paso De Blas",
  "Pasolo",
  "Poblacion",
  "Polo",
  "Punturin",
  "Rincon",
  "Tagalag",
  "Ugong",
  "Veinte Reales",
  "Wawang Pulo",
];

export const FIXED_ADDRESS = {
  region: "NCR",
  province: "Metro Manila",
  city: "Valenzuela",
};
